### PR TITLE
Started creating classes, added testing, and reorginized

### PR DESCRIPTION
**Pull request by Crebs**
* Started to create classes
* reorganized into Example, Classes, and Tests Directories
* Added beginning of our testing framework to help teach Sam about TDD (Test Driven Development)

### CODE REVIEW

**Comment by Tallsam20** [comment]
Cool

**Comment by Crebs** [comment]
Normally I wouldn't store the out file in the repo, but in this case there are a lot of stocks.  Storing all the output files in the repo can save time as we run the stock analysis repeatedly.

**Comment by Crebs** [comment]
@Tallsam20 FYI.

**Comment by Crebs** [comment]
There are over 4000 files now I'll just merge it as I don't think you'll want to look these over :P

**Pull request merged**
